server:
  port: 8003
spring:
  application:
    name: order-service
  profiles:
    include: feign
  cloud:
    nacos:
      server-addr: localhost:8849
      config:
        import-check:
          enabled: false

  data:
    redis:
      host: localhost
      port: 6379
      password: 123321
      timeout: 10000
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/charging_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 88888888
  # RabbitMQ 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 消息发送失败时返回给生产者
    publisher-returns: true
    publisher-confirm-type: correlated

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id