server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: localhost:8849
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        # 充电桩服务路由
        - id: station-service
          uri: lb://station-service
          predicates:
            - Path=/station/**

        # 订单服务路由
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
