server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: localhost:8849
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        # 用户服务路由（包括管理员登陆和用户管理）
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/admin/login,/admin/user/**

        # 充电桩服务路由
        - id: station-service
          uri: lb://station-service
          predicates:
            - Path=/station/**,/admin/station/**

        # 订单服务路由（包括订单管理）
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**,/admin/order/**,/charge/**
